version: "3"
services:
  bingus-api:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      bingus-encoder:
        condition: service_healthy
    ports:
      - 127.0.0.1:24789:8080
    volumes:
      - embedding-cache:/usr/src/app/embedding_cache
  bingus-encoder:
    build:
      context: ./bingus-python-encoder
    restart: unless-stopped
    volumes:
      - model-cache:/usr/src/app/model-cache
      - ./bingus-python-encoder/local-models:/usr/src/app/local-models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://bingus-encoder:5000/dimensions/"]
      interval: 1m
      timeout: 5s
      start_period: 2m
      start_interval: 1s
      retries: 5

volumes:
  model-cache:
  embedding-cache:
